### PR TITLE
feat(ui): networks-services view

### PR DESCRIPTION
**Pull request by decleaver**
services view

UDS:
image

openlens:
image

dashboard:
image

note: the uds view also matches what k9s returns for services

### CODE REVIEW

**Comment by BillyFigueroa** [comment]
@decleaver you can run `npm run format` in the ui folder and it will fix these linting errors for you

**Comment by Madeline-UX** [comment]
Create a new issue for the dense service view.

**Review by Madeline-UX — CHANGES_REQUESTED** [review]
- [ ] Add dash - to cells with no data
- [ ] - Add service status: write out the status (no color at this time

**Comment by decleaver** [comment]
updated uds view:
image

using the same logic as k8s dashboard to determine service status

**Comment by decleaver** [comment]
link to services dense view issue: https://github.com/defenseunicorns/uds-runtime/issues/64

**Review by jeff-mccoy — APPROVED** [review]
will need to update this once #28 is merged to use `?dense=true`

**Pull request merged**
