### PR TITLE
feat(ui): 435 truncated table cells

### PR DESCRIPTION
**Pull request by BillyFigueroa**
### Changes included in this PR
- [x] Converting table layout to a more fluid/ responsive non table layout
- [x] Adding sizing to every single table using the `DataTable` component
- [x] Moving all table column definitions for emphasizing first column to `Datatable`
- [x] Ensure truncation is added as tables re-size

### Changes not included in this PR
- [ ] This PR does not include converting the table pages that are not using the Datatable i.e. Pepr/ Event pages

## Related Issue

- #435 

### Before
Screenshot 2024-10-22 at 3 32 12 PM

### After
Screenshot 2024-10-22 at 3 43 52 PM

### CODE REVIEW

**Comment by decleaver** [comment]
Might have been missed on a merge, but the custom resources view needs to get updated with the new table
image

**Comment by decleaver** [comment]
the gateways view too:
image

**Comment by BillyFigueroa** [comment]
> Might have been missed on a merge, but the custom resource definitions view (and test) needs to get updated with the new table image

Updated
Screenshot 2024-11-08 at 10 20 57 AM

**Comment by BillyFigueroa** [comment]
> the gateways view too: image

Updated
Screenshot 2024-11-08 at 10 40 24 AM

**Review by UncleGedd — APPROVED** [review]
🚀 clicked through all the tables, looks good!

**Review by UncleGedd — APPROVED** [review]

**Pull request merged**
