### PR TITLE
chore(ui): merge playwright configs into single config file

### LINKED ISSUE #491: Merge Playwright Configs into Single File
We can merge all our playwright configs into the playwright.config.ts file by using projects:

examples (not the actual configs):
```typescript
import { defineConfig } from '@playwright/test';

const defaultConfig = {
  name: 'default',
  testDir: './tests',
  use: { baseURL: 'http://localhost:3000' },
};

const localAuthConfig = {
  ...defaultConfig,
  name: 'local-auth',
  use: { baseURL: 'http://localhost:3000/auth' },
};

const reconnectConfig = {
  ...defaultConfig,
  name: 'reconnect-tests',
  use: { baseURL: 'http://localhost:3000/reconnect' },
};

export default defineConfig({
  projects: [defaultConfig, localAuthConfig, reconnectConfig],
});
```
```json
{
  "scripts": {
    "test": "npx playwright test",
    "test:default": "npx playwright test --project=default",
    "test:local-auth": "npx playwright test --project=local-auth",
    "test:reconnect": "npx playwright test --project=reconnect-tests"
  }
}
```

### PR DESCRIPTION
**Pull request by TristanHoladay**
## Description
Turn playwright configs into projects in single config.ts file and reference in package.json scripts based on project name.

## Related Issue

Resolves #491

### CODE REVIEW

**Comment by TristanHoladay** [comment]
projects not acting as expected cause `webServer` field is allowed but not applied :angry:

**Comment by UncleGedd** [comment]
> projects not acting as expected cause `webServer` field is allowed but not applied 😠

dang, how is this not a thing yet: https://github.com/microsoft/playwright/issues/28054

**Comment by UncleGedd** [comment]
Love squashing the configs into a single file, is there any way around using an env var to swith configs? If not, let's just add some comments to the playwright config documenting what's going on

**Comment by TristanHoladay** [comment]
> Love squashing the configs into a single file, is there any way around using an env var to swith configs? If not, let's just add some comments to the playwright config documenting what's going on (maybe even use some TS types)

i did a lot of looking and experimenting but didn't see a playwright solution to this. i'll take another look, but i think we'll need the env var. if that's the case, i'll add the comments and see about some types.

**Pull request merged**
