### PR TITLE
chore: api testing adr

### PR DESCRIPTION
**Pull request by UncleGedd**
## Description

adds an API testing ADR

## Related Issue

- #77

### CODE REVIEW

**Review by decleaver — CHANGES_REQUESTED** [review]
I think also worth testing:
/api/v1/monitor/pepr
/api/v1/monitor/pepr/{stream}
/api/v1/monitor/cluster-overview

since they are handled differently than the mentioned bind groupings

**Comment by UncleGedd** [comment]
> I think also worth testing: /api/v1/monitor/pepr /api/v1/monitor/pepr/{stream} /api/v1/monitor/cluster-overview
> 
> since they are handled differently than the mentioned bind groupings

updated!

**Review by decleaver — CHANGES_REQUESTED** [review]
thoughts on breaking it down even more and just testing a corev1 type and a custom resource type? I think the handlers for the corev1 types are all the same, and same thing with the custom resources. Would also cover the dynamic and shared informer paths

**Review by decleaver — APPROVED** [review]
👍

**Pull request merged**
