### PR TITLE
chore: rename LICENSE to LICENSE.md

### PR DESCRIPTION
**Pull request by nywilken**
This change updates the LICENSE file to match the link within LICENSING.md.

### CODE REVIEW

**Review by UncleGedd — APPROVED** [review]
thank you!

**Review by jeff-mccoy — APPROVED** [review]

**Comment by UncleGedd** [comment]
@nywilken looks like one of your commits isn't signed, happy to help get this pushed through

**Comment by nywilken** [comment]
@UncleGedd I rebased and signed the commit. Feel free to merge if this was the blocker. Otherwise I can sync with you tomorrow on the expectations for commits. 

https://github.com/defenseunicorns/uds-runtime/pull/477/commits/a39dd69e8c4c58557b6c26dfabcbfa45afbf09ca

**Comment by UncleGedd** [comment]
> @UncleGedd I rebased and signed the commit. Feel free to merge if this was the blocker. Otherwise I can sync with you tomorrow on the expectations for commits.
> 
> [a39dd69](https://github.com/defenseunicorns/uds-runtime/commit/a39dd69e8c4c58557b6c26dfabcbfa45afbf09ca)

Hey @nywilken you should see the green "Verified" emblem next to your commit hash, yours is still showing as not verified. Happy to sync up tomorrow

**Comment by nywilken** [comment]
> > @UncleGedd I rebased and signed the commit. Feel free to merge if this was the blocker. Otherwise I can sync with you tomorrow on the expectations for commits.
> > [a39dd69](https://github.com/defenseunicorns/uds-runtime/commit/a39dd69e8c4c58557b6c26dfabcbfa45afbf09ca)
> 
> Hey @nywilken you should see the green "Verified" emblem next to your commit hash, yours is still showing as not verified. Happy to sync up tomorrow

Oh okay thanks for this clarification. Today I learned that I can use SSH as the signing key. Let's quickly sync on this today.

**Pull request merged**
